'use server';

/**
 * @fileOverview This file defines a Genkit flow for answering common questions about postpartum care and baby advice.
 *
 * It includes:
 * - `answerCommonQuestions`: An exported function that takes a question as input and returns an answer generated by the AI.
 * - `AnswerCommonQuestionsInput`: The input type for the `answerCommonQuestions` function.
 * - `AnswerCommonQuestionsOutput`: The output type for the `answerCommonQuestions` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerCommonQuestionsInputSchema = z.object({
  question: z.string().describe('The question to be answered.'),
});
export type AnswerCommonQuestionsInput = z.infer<typeof AnswerCommonQuestionsInputSchema>;

const AnswerCommonQuestionsOutputSchema = z.object({
  answer: z.string().describe('The answer to the question.'),
});
export type AnswerCommonQuestionsOutput = z.infer<typeof AnswerCommonQuestionsOutputSchema>;

export async function answerCommonQuestions(input: AnswerCommonQuestionsInput): Promise<AnswerCommonQuestionsOutput> {
  return answerCommonQuestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerCommonQuestionsPrompt',
  input: {schema: AnswerCommonQuestionsInputSchema},
  output: {schema: AnswerCommonQuestionsOutputSchema},
  prompt: `You are a helpful chatbot designed to answer common questions from new mothers about postpartum care and baby advice.

  Question: {{{question}}}

  Answer: `,
});

const answerCommonQuestionsFlow = ai.defineFlow(
  {
    name: 'answerCommonQuestionsFlow',
    inputSchema: AnswerCommonQuestionsInputSchema,
    outputSchema: AnswerCommonQuestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
