'use server';

/**
 * @fileOverview This file defines a Genkit flow for answering common questions about postpartum care and baby advice.
 *
 * It includes:
 * - `answerCommonQuestions`: An exported function that takes a question as input and returns an answer generated by the AI.
 * - `AnswerCommonQuestionsInput`: The input type for the `answerCommonQuestions` function.
 * - `AnswerCommonQuestionsOutput`: The output type for the `answerCommonQuestions` function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnswerCommonQuestionsInputSchema = z.object({
  question: z.string().describe('The question to be answered.'),
});
export type AnswerCommonQuestionsInput = z.infer<typeof AnswerCommonQuestionsInputSchema>;

const AnswerCommonQuestionsOutputSchema = z.object({
  answer: z.string().describe('The answer to the question.'),
});
export type AnswerCommonQuestionsOutput = z.infer<typeof AnswerCommonQuestionsOutputSchema>;

export async function answerCommonQuestions(input: AnswerCommonQuestionsInput): Promise<AnswerCommonQuestionsOutput> {
  return answerCommonQuestionsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'answerCommonQuestionsPrompt',
  input: {schema: AnswerCommonQuestionsInputSchema},
  output: {schema: AnswerCommonQuestionsOutputSchema},
  prompt: `Você é a NathIA, uma assistente virtual, amiga e mentora para mães. Sua personalidade é extremamente acolhedora, empática, amorosa e cuidadosa. Você é uma especialista em maternidade, fé e bem-estar, inspirada nos valores e no conteúdo de Nathália Valente.
  
  Seu objetivo é fazer com que cada mãe se sinta ouvida, compreendida e apoiada. Use uma linguagem próxima, carinhosa e cheia de positividade. Trate cada pergunta como uma conversa com uma amiga querida.

  Question: {{{question}}}

  Answer: `,
});

const answerCommonQuestionsFlow = ai.defineFlow(
  {
    name: 'answerCommonQuestionsFlow',
    inputSchema: AnswerCommonQuestionsInputSchema,
    outputSchema: AnswerCommonQuestionsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
